"""
GUIDANCE: INTEGRATED GRADIENTS (IG) DISTRIBUTION ANALYSIS
This script reads the precomputed attribution scores generated by the 
PITCH pipeline and utilizes standard SHAP visualization tools to plot 
the global importance of each feature. This demonstrates that IG scores 
can be treated mathematically similarly to SHAP values, but calculated 
much faster for large biological datasets.
"""

import os
import h5py
import numpy as np
import shap
import argparse
import matplotlib.pyplot as plt

def parse_arguments():
    parser = argparse.ArgumentParser()
    # PATH UPDATES: Points to the EGF data directory by default
    parser.add_argument('--data_dir', type=str, default=os.path.join('..', 'data', 'EGF_perturb'))
    parser.add_argument('--response', type=int, default=3)
    parser.add_argument('--concentrate_idx', type=int, default=1)
    return parser.parse_args()

def get_correlation3(X, Y):
    """
    GUIDANCE: Standardizes and calculates dot product correlation between 
    inputs and attributions to identify strong linear relationships.
    """
    Y_std = np.sqrt(np.sum((Y - np.mean(Y, axis=0)) ** 2, axis=0))
    X_std = np.sqrt(np.sum((X - np.mean(X, axis=0)) ** 2, axis=0))
    
    # Avoid division by zero
    X_std[X_std == 0] = 1e-8
    Y_std[Y_std == 0] = 1e-8
    
    X_standardized = (X - np.mean(X, axis=0)) / X_std
    Y_standardized = (Y - np.mean(Y, axis=0)) / Y_std
    
    correlations_np = np.sum(X_standardized * Y_standardized, axis=0)
    return correlations_np

def main():
    args = parse_arguments()

    # Setup directories
    plot_dir = os.path.join(args.data_dir, 'plots')
    os.makedirs(plot_dir, exist_ok=True)

    print(f"Loading data from {args.data_dir}...")
    mat = h5py.File(os.path.join(args.data_dir, 'Data_1.mat'), 'r')
    LinearIndex = np.array(mat['LinearIndex']).T.squeeze()
    
    feat_path = os.path.join(args.data_dir, 'FeatureData-z-510.npy')
    FeatureData = np.load(feat_path)
    
    concentration = [0, 1, 6.25, 10, 25, 100]
    con_idx = args.concentrate_idx
    response_idx = args.response

    # ==========================================
    # Load Precomputed Attributions
    # ==========================================
    # GUIDANCE: These matrices should have been generated by earlier PITCH pipeline steps.
    # W represents the raw gradients; attr represents Gradients * (Input - Baseline)
    try:
        W = np.load(os.path.join(args.data_dir, f'W_{response_idx}-{concentration[con_idx]}-dim510-z.npy'))
        attr = np.load(os.path.join(args.data_dir, f'attr_{response_idx}-{concentration[con_idx]}-dim510-z.npy'))
        X_ig = np.load(os.path.join(args.data_dir, f'X_ig_{response_idx}-{concentration[con_idx]}-dim510-z.npy'))
    except FileNotFoundError:
        print(f"ERROR: Precomputed attribution files not found in {args.data_dir}.")
        print("Please ensure the IG computation script has been run first.")
        return

    # Load feature names
    feat_names = []
    feat_name_path = os.path.join(args.data_dir, 'feature_name.txt')
    if os.path.exists(feat_name_path):
        with open(feat_name_path, 'r') as file:
            for line in file:
                feat_names.append(line.strip())
    else:
        feat_names = [f"Feature_{i}" for i in range(X_ig.shape[1])]

    # ==========================================
    # Generate SHAP-style Summary Plots
    # ==========================================
    print("Generating SHAP-style summary plots for Integrated Gradients...")
    
    # 1. Plot Full Attribution (Input * Gradient)
    shap.summary_plot(attr, X_ig, max_display=20, color_bar=True, plot_size=(16, 10), 
                      color_bar_label='Feature value', show=False, feature_names=feat_names)
    plt.xlabel('Integrated Gradient Value Distribution (Full Attribution)')
    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, f'shap_{response_idx}-{concentration[con_idx]}_attr.svg'), format='svg')
    plt.close()

    # 2. Plot Raw Gradients / Weights
    shap.summary_plot(W, X_ig, max_display=20, color_bar=True, plot_size=(16, 10), 
                      color_bar_label='Feature value', show=False, feature_names=feat_names)
    plt.xlabel("Gradient Value Distribution (Without Input Multiplier)")
    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, f'shap_{response_idx}-{concentration[con_idx]}_W.svg'), format='svg')
    plt.close()

    # ==========================================
    # Output Key Biological Insights
    # ==========================================
    positive_mask = W > 0
    positive_counts = np.sum(positive_mask, axis=0)
    print(f"\n--- Insights for {concentration[con_idx]} ng/mL ---")
    print('Features with exclusively positive coefficients:', np.where(positive_counts == W.shape[0])[0])
    print('Features with exclusively negative coefficients:', np.where(positive_counts == 0)[0])

    # GUIDANCE: High correlation between raw inputs and IG scores indicates a linear pathway.
    cor = get_correlation3(X_ig, attr)
    highly_correlated = np.where(cor > 0.8)[0]
    print(f'Features highly linearly correlated (r > 0.8) with their IG score: {highly_correlated}')
    print(f"Saved plots to {plot_dir}")

if __name__ == '__main__':
    main()